### ISSUE TITLE
npm start fails on fresh setup

### ISSUE THREAD

**Issue by codyburleson** [ionic-team/stencil-starter#49]
**Stencil version:** 

```
@stencil/starter@0.0.1 /Users/cburleson/repos/cburleson-platform
└── @stencil/core@0.7.22
```

**I'm submitting a ...**  (check one with "x")
[ X] bug report

**Current behavior:**

On a fresh setup of the Stencil App Starter on Mac, I'm getting the following error on `npm start` (whether with node 8,9, or 10)...

```
[ ERROR ]  Cannot find module 'resolve' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15) at
           Function.Module._load (internal/modules/cjs/loader.js:497:25) at Module.require
           (internal/modules/cjs/loader.js:626:17) at require (internal/modules/cjs/helpers.js:20:18) at
           Object.<anonymous>
           (/Users/cburleson/repos/cburleson-platform/node_modules/@stencil/core/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:10:15)
           at Module._compile (internal/modules/cjs/loader.js:678:30) at Object.Module._extensions..js
           (internal/modules/cjs/loader.js:689:10) at Module.load (internal/modules/cjs/loader.js:589:32) at
           tryModuleLoad (internal/modules/cjs/loader.js:528:12) at Function.Module._load
           (internal/modules/cjs/loader.js:520:3)
```

**Expected behavior:**

I expect the build to complete and the starter web app to load in my browser,

**Comment by codyburleson** [comment]
This is resolved by changing the `@stencil/core` dependency to `^0.7.27-4`. I will leave the issue open, however, as I think this should be resolved in the code base for other users.

**Comment by silentHoo** [comment]
@jgw96: Ping.

**Comment by tvvignesh** [comment]
Same issue here.
